#!/usr/bin/env node

import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const backendRoot = join(import.meta.dirname, "..");
const routesDir = join(backendRoot, "src/routes");
const outputFile = join(backendRoot, "src/routes/register.generated.ts");

const httpMethods = ["GET", "POST", "PATCH", "PUT", "DELETE"];

function walk(dir) {
  const entries = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) {
      entries.push(...walk(full));
    } else if (name === "route.ts") {
      entries.push(full);
    }
  }
  return entries;
}

function toApiPath(filePath) {
  const rel = relative(routesDir, filePath).replace(/\\/g, "/");
  const segments = rel.replace(/\/route\.ts$/, "").split("/");
  return (
    "/api/" +
    segments
      .map((segment) =>
        segment.startsWith("[") && segment.endsWith("]")
          ? `:${segment.slice(1, -1)}`
          : segment
      )
      .join("/")
  );
}

function toImportPath(filePath) {
  const rel = relative(join(backendRoot, "src"), filePath)
    .replace(/\\/g, "/")
    .replace(/\.ts$/, "");
  return `@/${rel}`;
}

function detectMethods(source) {
  return httpMethods.filter((method) =>
    source.includes(`export async function ${method}`)
  );
}

const routeFiles = walk(routesDir);
const imports = [];
const registrations = [];

routeFiles.forEach((file, index) => {
  const source = readFileSync(file, "utf8");
  const methods = detectMethods(source);
  if (methods.length === 0) return;

  const alias = `route${index}`;
  imports.push(`import * as ${alias} from "${toImportPath(file)}";`);
  const path = toApiPath(file);

  for (const method of methods) {
    registrations.push(
      `  router.${method.toLowerCase()}("${path}", adaptRoute(${alias}.${method}));`
    );
  }
});

const content = `/* eslint-disable import/order */
// Auto-generated by scripts/generate-routes.mjs — do not edit manually.
import { Router } from "express";
import { adaptRoute } from "@/lib/http/route-handler";

${imports.join("\n")}

export function registerRoutes(): Router {
  const router = Router();
${registrations.join("\n")}
  return router;
}
`;

writeFileSync(outputFile, content);
console.log(`Generated ${registrations.length} route registrations`);
